package main

const (
	MAP_WIDTH  int = 1280
	MAP_HEIGHT int = 1280

	FPS int = 60

	PLAYER_HEALTH   int = 10
	PLAYER_WIDTH    int = 40
	PLAYER_HEIGHT   int = 40
	PLAYER_VELOCITY int = 40

	MONSTER_WIDTH    int = 44
	MONSTER_HEIGHT   int = 31
	MONSTER_VELOCITY int = 3
	MONSTER_HEALTH   int = 3
	MONSTER_DAMAGE   int = 1

	PROJECTILE_WIDTH    int = 6
	PROJECTILE_HEIGHT   int = 16
	PROJECTILE_VELOCITY int = 10
	PROJECTILE_DAMAGE   int = 1
)
